if vim.g.vscode then
  return {}
else
  return {
    -- add gruvbox
    -- { "ellisonleao/gruvbox.nvim", opts = {
    --   contrast = "hard",
    -- } },
    --
    -- -- Configure LazyVim to load gruvbox
    -- {
    --   "LazyVim/LazyVim",
    --   opts = {
    --     colorscheme = "gruvbox",
    --   },
    -- },

    -- {
    --   "navarasu/onedark.nvim",
    --   priority = 1000, -- make sure to load this before all the other start plugins
    --   config = function()
    --     require("onedark").setup({
    --       style = "darker",
    --     })
    --     -- Enable theme
    --     require("onedark").load()
    --   end,
    -- },

    -- {
    --   "rebelot/kanagawa.nvim",
    --   config = function()
    --     require("kanagawa").setup({
    --       -- You can add Kanagawa-specific configurations here
    --     })
    --     vim.cmd("colorscheme kanagawa")
    --   end,
    -- },
    -- {
    --   "kepano/flexoki-neovim",
    --   name = "flexoki",
    --   config = function()
    --     vim.cmd("colorscheme flexoki")
    --   end,
    -- },

    --
    -- {
    --   "LazyVim/LazyVim",
    --   opts = {
    --     colorscheme = "onelight",
    --   },
    -- },
    -- {
    --   "olimorris/onedarkpro.nvim",
    --   priority = 1000,
    -- },
    -- {
    --   "LazyVim/LazyVim",
    --   opts = {
    --     colorscheme = { "onelight", "onedark_dark" },
    --   },
    -- },
    -- return {
    --   {
    --     "newtoallofthis123/monokai-pro-light.nvim",
    --     config = function()
    --       require("monokai-pro").setup({})
    --     end,
    --   },
    --   -- {
    --   --   "olimorris/onedarkpro.nvim",
    --   --   priority = 1000, -- Ensure it loads first
    --   --   -- config = function()
    --   --   --   vim.cmd("colorscheme onedark_dark")
    --   --   -- end,
    --   -- },
    --   -- {
    --   --   "tiagovla/tokyodark.nvim",
    --   --   config = function(_, opts)
    --   --     require("tokyodark").setup(opts) -- calling setup is optional
    --   --     vim.cmd([[colorscheme tokyodark]])
    --   --   end,
    --   -- },
    --   -- {
    --   --   "projekt0n/github-nvim-theme",
    --   --   lazy = false, -- make sure we load this during startup if it is your main colorscheme
    --   --   priority = 1000, -- make sure to load this before all the other start plugins
    --   --   -- config = function()
    --   --   --   require("github-theme").setup({
    --   --   --     -- ...
    --   --   --   })
    --   --   --
    --   --   --   vim.cmd("colorscheme github_dark_high_contrast")
    --   --   -- end,
    --   -- },
    -- }
  }
end
